on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache for Maven Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-mvn
          restore-keys: |
            ${{ runner.os }}-mvn
      - name: Grant execution permissions for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
